name: Create/Update QR counter release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create release and upload pixel asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: qr-counter
          name: QR Counter
          draft: false
          prerelease: false
          files: |
            assets/pixel.gif


